### ISSUE TITLE
Does not appear to be compatible with the current version of Lightning

### ISSUE THREAD

**Issue by import-antigravity** [ray-project/ray_lightning_accelerators#8]
I was excited to try this out but the code appears to not be working due to a missing import:

```
Traceback (most recent call last):
  File "...", line 9, in <module>
    from ray_lightning import RayAccelerator
  File ".../lib/python3.8/site-packages/ray_lightning/__init__.py", line 1, in <module>
    from ray_lightning.ray_ddp import RayAccelerator
  File ".../lib/python3.8/site-packages/ray_lightning/ray_ddp.py", line 8, in <module>
    from pytorch_lightning.accelerators import DDPSpawnAccelerator
ImportError: cannot import name 'DDPSpawnAccelerator' from 'pytorch_lightning.accelerators' (.../lib/python3.8/site-packages/pytorch_lightning/accelerators/__init__.py)
```

**Comment by amogkam** [comment]
Hi @import-antigravity, thanks for posting this issue! The PTL team actually did a major refactor of their accelerator code in the 1.2 release. I am currently working on updating this library to be compatible with their changes, but until that is done can you try with pytorch lightning v1.1.8.

**Comment by import-antigravity** [comment]
Unfortunately my code is susceptible to a bug which was fixed in 1.2

**Comment by amogkam** [comment]
Ah that's unfortunate. Ok I will make sure to update you here once we have compatibility with 1.2 which should be in the next few days.

**Comment by amogkam** [comment]
Alternatively, you could maybe build pytorch lightning from source and cherry pick just the commit that fixes the bug onto the 1.1.8 code.

**Comment by import-antigravity** [comment]
No worries, I can survive only running jobs on a single node for a few days. Would using this package by chance also solve this issue?
https://github.com/PyTorchLightning/pytorch-lightning/issues/3651

**Comment by amogkam** [comment]
Unfortunately even using this library, running on SLURM would still result in that error I believe. As mentioned by @richardliaw in https://github.com/ray-project/ray/issues/10995, ideally PTL provides a way to turn off automatic slurm detection since we don't want to use their SlurmConnector when using Ray.

I think the hack mentioned in https://github.com/ray-project/ray/issues/10995 should still work, though you would have to make sure to set the environment variable in all of the workers as well. You can do this by passing in a `init_hook` to your `RayAccelerator`. So something like this

```
def disable_slurm():
    os.environ["SLURM_JOB_NAME"] = "bash"

accelerator = RayAccelerator(..., init_hook=disable_slurm)
```

I'll also make an issue for this on PTL to see if we can add a way to turn off automatic slurm detection.

**Comment by import-antigravity** [comment]
> Ah that's unfortunate. Ok I will make sure to update you here once we have compatibility with 1.2 which should be in the next few days.

Hey, do you have an update on this?

**Comment by amogkam** [comment]
Hey sorry I was sick for most of last week. It's currently in progress here https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/accelerator_connector.py#L400

**Comment by amogkam** [comment]
@import-antigravity https://github.com/ray-project/ray_lightning_accelerators/pull/15 has been merged. This library should now work with PTL 1.2.4.

**Comment by import-antigravity** [comment]
> @import-antigravity #15 has been merged. This library should now work with PTL 1.2.4.

🙌 🙌 🙌 🙌 🙌 🙌 🙌 🙌
